config/routes.rb
Rails.application.routes.draw do
  # Define a rota raiz para a página inicial
  root "home#index"
  
  # Rotas do Devise para autenticação
  devise_for :users
  
  resources :produtos
  

  post '/pagamento', to: 'pagamentos#create', as: :pagamento
  get '/pagamento/finalizar', to: 'pagamentos#finalizarpagamento', as: :pagamento_show
  
  get '/', to: 'home#index', as: :home
  get '/pagamento/sucesso', to: 'pagamentos#sucesso', as: :pagamento_sucesso
  get '/pagamento/erro', to: 'pagamentos#erro', as: :pagamento_erro
  get '/pagamento/processando', to: 'pagamentos#processando', as: :pagamento_processando
  
  # Rotas do carrinho
  resource :cart, only: [:show] do
    post 'add_item/:produto_id', to: 'carts#add_item', as: :add_item
    delete 'remove_item/:item_id', to: 'carts#remove_item', as: :remove_item
  end


  # Rotas de pedidos
  resources :orders, only: [:index, :show, :create]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/produto.rb
class Produto
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
  field :preco, type: Integer
  field :descricao, type: String
  field :foto, type: String
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<%= form_with(model: produto) do |form| %>
  <% if produto.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
        <% produto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :preco, style: "display: block" %>
    <%= form.number_field :preco %>
  </div>

  <div>
    <%= form.label :descricao, style: "display: block" %>
    <%= form.text_field :descricao %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/produtos/_produto.html.erb
<div id="<%= dom_id produto %>" class="card mb-3">
  <%# Removido código antigo e aplicado Bootstrap %>
  <%= image_tag produto.foto, class: "card-img-top", alt: produto.name %>
  <div class="card-body">
    <h5 class="card-title"><%= produto.name %></h5>
    <p class="card-text"><strong>Preço:</strong> R$ <%= produto.preco %></p>
    <p class="card-text"><strong>Descrição:</strong> <%= produto.descricao %></p>
  </div>
</div>

app/views/produtos/edit.html.erb
<% content_for :title, "Editing produto" %>

<h1>Editing produto</h1>

<%= render "form", produto: @produto %>

<br>

<div>
  <%= link_to "Show this produto", @produto %> |
  <%= link_to "Back to produtos", produtos_path %>
</div>

app/views/produtos/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Produtos" %>

<h1 class="mb-4">Produtos</h1>

<div class="row row-cols-1 row-cols-md-3 g-4" id="produtos">
  <% @produtos.each do |produto| %>
    <div class="col">
      <%= render produto %>
      <p>
        <%= link_to "Show this produto", produto %>
      </p>
    </div>
  <% end %>
</div>

<%= link_to "New produto", new_produto_path %>

app/views/produtos/new.html.erb
<% content_for :title, "New produto" %>

<h1>New produto</h1>

<%= render "form", produto: @produto %>

<br>

<div>
  <%= link_to "Back to produtos", produtos_path %>
</div>

app/views/produtos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @produto %>

<div>
  <%= link_to "Edit this produto", edit_produto_path(@produto) %> |
  <%= link_to "Back to produtos", produtos_path %>

  <%= button_to "Destroy this produto", @produto, method: :delete %>
</div>